routes/web.php
<?php

use App\Http\Controllers\Admin\MatchesController;
use App\Http\Controllers\Admin\ScoresController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BetController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RankingController;
use App\Http\Controllers\TeamsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [HomeController::class, 'index'])->name('homepage');

Route::middleware(['guest'])->group(function () {
    Route::get('/login', [AuthController::class, 'loginView'])->name('login-view')->middleware('guest');
    Route::post('/login', [AuthController::class, 'login'])->name('login')->middleware('guest');
    Route::get('/signin', [AuthController::class, 'signinView'])->name('signin-view');
    Route::post('/signin', [AuthController::class, 'signin'])->name('signin');
});


Route::middleware(['auth'])->group(function () {
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('rankings', [RankingController::class, 'index'])->name('rankings');

    Route::get('bet/{theMatch}/list', [BetController::class, 'list'])->name('bets-list');
    Route::get('bet/{theMatch}', [BetController::class, 'index'])->name('match-bet');
    Route::get('bet/{theMatch}/{winnerChoice}', [BetController::class, 'create'])->name('create-bet');

    Route::middleware(['isAdmin'])->group(function () {
        Route::get('admin/matches', [MatchesController::class, 'index'])->name('matches');
        Route::get('admin/teams', [TeamsController::class, 'index'])->name('teams');
        Route::post('admin/teams', [TeamsController::class, 'create'])->name('create-team');
        Route::post('admin/matches', [MatchesController::class, 'create'])->name('create-match');

        Route::get('admin/scores/{theMatch?}', [ScoresController::class, 'index'])->name('scores');
        Route::post('admin/scores/{theMatch}/create', [ScoresController::class, 'create'])->name('create-score');
    });
});

app/Models/TheMatch.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class TheMatch extends Model
{

    const PAIR = 0;

    use HasFactory;

    protected $table = 'matches';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'team_1',
        'team_2',
        'date_start'
    ];

    public function team1()
    {
        return $this->hasOne(Team::class, 'id', 'team_1');
    }

    public function team2()
    {
        return $this->hasOne(Team::class, 'id', 'team_2');
    }

    public function scopeEndedMatches($query)
    {
        $now = Carbon::now();
        return $query->whereRaw("DATE_ADD(date_start, INTERVAL 2 HOUR) < '{$now}'");
    }

    public function scopeWithoutWinner($query)
    {
        return $query->whereNull('winner_id');
    }

    public function userHasBet()
    {
        return $this->hasOne(Bet::class, 'match_id', 'id')->where('user_id', Auth::user()->id);
    }

    public function bets()
    {
        return $this->hasMany(Bet::class, 'match_id', 'id');
    }

    public function winnerTeam()
    {
        return $this->hasOne(Team::class, 'id', 'winner_id');
    }

    public function getIsFinishedAttribute()
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $this->date_start)->add('2 hour')->format('Y-m-d H:i:s') < Carbon::now();
    }

    public function getIsPlayingAttribute()
    {
        return Carbon::now() > Carbon::createFromFormat('Y-m-d H:i:s', $this->date_start) &&
            Carbon::now() < Carbon::createFromFormat('Y-m-d H:i:s', $this->date_start)->add('2 hour')->format('Y-m-d H:i:s');
    }

    public function getIsBettableAttribute()
    {
        return Carbon::now()->lessThan(Carbon::parse($this->date_start)->sub('30 minutes'));
    }

    static public function boot()
    {
        parent::boot();

        self::updated(function (TheMatch $theMatch) {
            $bets = $theMatch->bets()->get();
            $bets->each(function ($bet) use ($theMatch) {
                if ($bet->bet === $theMatch->winner_id) {
                    $user = $bet->user()->first();
                    $user->points++;
                    $user->save();
                }
            });
        });
    }
}

resources/views/bet-list.blade.php
@extends('layouts/master')

@section('title', $title)

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <h3 class="card-title text-center">Bet List for match #{{ $match->id }} - {{ $match->team1->name }} <i class="fa fa-close fa-fw"></i> {{ $match->team2->name }} </h3>
                <div class="card-body">

                    <table class="table table-hover table-bordered">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>User</th>
                            <th>Bet</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if ($match->bets->count() == 0)
                            <tr>
                                <td colspan="4">No Bet to display.</td>
                            </tr>
                        @endif


                        @foreach($match->bets as $index => $bet)

                            <tr>
                                <td>{{ ($match->bets->currentpage()-1) * $match->bets->perpage() + $loop->index + 1 }}</td>
                                <td>{{ $bet->user->name }}</td>
                                <td>{{ $bet->betTeam->name }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    {{ $match->bets->links('vendor.pagination.bootstrap-4') }}

                    <p>
                        Displaying {{$match->bets->count()}} of {{ $match->bets->total() }} team(s).
                    </p>
                </div>
            </div>
        </div>

    </div>

@endsection

@section('script')

@endsection

resources/views/bet.blade.php
@extends('layouts/master')

@section('title', $title)

@section('content')

    @if($errors->has('error'))
        <div class="row">
            <div class="col-md-12">
                <span class="alert-danger text-center">{{ $errors->first('error') }}</span>
            </div>
        </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="justify-content-center">
                <div class="card">
                    <h3 class="card-title text-center">
                        {{ $match->team1->name }} <i class="fa fa-close fa-fw"></i> {{ $match->team2->name }} - {{ $match->date_start }}
                    </h3>
                    <div class="card-body">

                        @if($match->userHasBet)
                            <span class="alert-danger text-center">You have already bet on this match!</span>
                        @else
                            <div class="row">
                                <div class="col-md-4 mb-3">
                                    <a class="btn btn-block btn-outline-success" href="{{ route('create-bet', [$match->id, $match->team1->id]) }}">{{ $match->team1->name }}</a>
                                </div>
                                <div class="col-md-4 mb-3">
                                    <a class="btn btn-block btn-outline-success" href="{{ route('create-bet', [$match->id, 0]) }}">Pair</a>
                                </div>
                                <div class="col-md-4 mb-3">
                                    <a class="btn btn-block btn-outline-success" href="{{ route('create-bet', [$match->id, $match->team2->id]) }}">{{ $match->team2->name }}</a>
                                </div>
                            </div>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script')

@endsection

resources/views/homepage.blade.php
@extends('layouts/master')

@section('title', $title)

@section('content')

    <h3 class="text-center">Match List - Time: <span class="datetime"></span></h3>
    <div class="row">
        @foreach($matches as $match)

            <div class="col-md-6 mb-3">
                <div class="card @if($match->is_playing) border-success @elseif($match->is_finished) border-danger @else border-secondary @endif">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4 font-weight-bolder">
                                {{ $match->team1->name }} - {{ $match->team2->name }}
                            </div>
                            <div class="col-md-4">
                               @if($match->is_finished)
                                    @if($match->winner_id === 0)
                                        Pair
                                    @elseif ($match->winner_id === null)
                                        @if(auth()->user() && auth()->user()->is_admin)
                                            Winner: <a href="{{ route('scores', ['theMatch' => $match->id]) }} "> <span class="text-secondary">Not set</span> </a>
                                        @else
                                            Winner:  <span class="text-secondary">Not set</span>
                                        @endif
                                    @else
                                        Winner: <span class="text-success"> {{$match->winnerTeam->name}}</span>
                                    @endif
                                @endif

                            </div>
                            <div class="col-md-4">

                                @if($match->is_playing)
                                    <span class="running-game text-success"><i class="fa fa-play-circle"></i> Playing </span> <span class="text-dark play-time pull-right" data-start="{{ $match->date_start }}"></span>
                                @endif

                                @if($match->is_finished)
                                        <span class="text-danger"><i class="fa fa-close"></i> Finished</span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-md-8">
                                Match start: {{ date('j F, Y H:i', strtotime($match->date_start)) }}
                            </div>

                            @if(auth()->user())

                                @if(date('Y-m-d H:i:s', strtotime('+30 minutes')) > date($match->date_start))
                                    <div class="col-md-4">
                                        <a class="btn btn-primary btn-block btn-sm" href="{{ route('bets-list', $match->id) }}">
                                            Show bets
                                        </a>
                                    </div>
                                @endif
                                @if($match->is_bettable)
                                    <div class="col-md-4">
                                        @if(array_key_exists($match->id, $user_bets))
                                            <span class="text-danger">Already bet</span>
                                        @else
                                            <a class="btn btn-block btn-outline-primary btn-sm"
                                               href="{{ route('match-bet', $match->id) }}">Bet</a>
                                        @endif
                                    </div>
                                @endif
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    <div class="row">
        <div class="col-md-12 d-flex justify-content-center">
            {{ $matches->links('vendor.pagination.bootstrap-4') }}
        </div>
        <div class="col-md-12">
            <p>
                Displaying {{$matches->count()}} of {{ $matches->total() }} Match(s).
            </p>
        </div>
    </div>

@endsection

@section('script')
    <script>
        $(document).ready(function() {
            setInterval(function() {
                var momentNow = moment();
                $('.datetime').html(momentNow.format('DD/MM/YYYY - HH:mm:ss'));

                if (momentNow.format('ss') === '00') {
                    setTimeout(function () {
                    window.location.reload();
                    }, 1000)
                }
            }, 100);

            setInterval(function () {
                $('.play-time').each(function (){
                    let start = moment($(this).data('start'));
                    $(this).html(pad(moment.duration(moment().diff(start)).hours()) +':'+pad(moment.duration(moment().diff(start)).minutes()) +':'+ pad(moment.duration(moment().diff(start)).seconds()));
                })
            }, 500)
        });

        function pad (str, max) {
            if (!max) max = 2
            str = str.toString();
            return str.length < max ? pad("0" + str, max) : str;
        }
    </script>
@endsection

resources/views/rankings.blade.php
@extends('layouts/master')

@section('title', $title)

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <h3 class="card-header text-center">User Ranking</h3>
                <div class="card-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <th>User Name</th>
                        <th>Points</th>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                        <tr>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->points }}</td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    {{ $users->links('vendor.pagination.bootstrap-4') }}

                    <p>
                        Displaying {{$users->count()}} of {{ $users->total() }} user(s).
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

@endsection